name = input ("what is your name? ")
print(name , "thats an ugly name for a girl")
age = input ("how old are you? ")
print(age , "you are old ")
fun = input ("what do you do for fun? ")
print(fun , "thats boring ")
music = input ("what kind of music do you like? ")
print( music , "hats stupid why cant you just pick one type ")
siblings = input ("how many siblings do you have? ")
print(siblings , "that sucks ")
grown = input ("what do you want to be when you grow up? ")
print( grown , "yeah good luck with that ")
